spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false
      retry:
        initial-interval: 1000
        max-attempts: 3
        max-interval: 5000
        multiplier: 1.5

  datasource:
    username: acdevs
    password: 4444
    url: jdbc:postgresql://localhost:5432/catalog
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5

  sql:
    init:
      mode: always

server:
  port: 8080
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 10s
    threads:
      max: 100
      min-spare: 5

catalog:
  greeting: Hello from local Catalog Service!